import Head from "next/head";
import Image from "next/image";
import { useUser, useSupabaseClient } from "@supabase/auth-helpers-react";
import { useRef } from "react";

export default function Home() {
  const inputRef = useRef();
  const supabase = useSupabaseClient();
  const user = useUser();

  async function signInWithSpotify() {
    try {
      const { error, data } = await supabase.auth.signInWithOAuth({
        provider: "spotify",
      });
      if (error) {
        alert("Error with auth: " + error.message);
      }
    } catch {
      console.log("error", error);
      alert(error.error_description || error);
    }
  }

  function searchSpotify(e) {
    e.preventDefault();
    const searchValue = inputRef.current.value;
    console.log(searchValue)
    // fetch("/api/search", {
    //   method: "POST",
    //   headers: { "Content-Type": "application/json" },
    //   body: JSON.stringify({
    //     query: searchValue
    //   })
    // }).then(async (response) => {
    //   if (response.ok) {
        
    //   } else {
        
    //   }
    // });
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class="bg-spotifyBlack">
        {user ? (
          <nav class="container relative mx-auto p-3 text-white">
            <div class="flex items-center justify-between">
              <div>
                <p>Logo</p>
              </div>

              <div className="w-[40rem]">
                <form onSubmit={searchSpotify}>
                  <label
                    for="default-search"
                    class="sr-only mb-2 text-sm font-medium text-gray-900 dark:text-white"
                  >
                    Search
                  </label>
                  <div class="relative">
                    <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                      <svg
                        aria-hidden="true"
                        class="h-5 w-5 text-gray-500 dark:text-gray-400"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                        ></path>
                      </svg>
                    </div>
                    <input
                      ref={inputRef}
                      type="search"
                      id="default-search"
                      class="block w-full rounded-3xl border border-gray-300 bg-gray-50 p-3 pl-10 text-sm text-gray-900"
                      placeholder="Search artist, song, album..."
                      required
                    />
                    {/* <button
                      type="submit"
                      class="absolute right-2.5 bottom-2.5 rounded-lg bg-spotifyGreen px-4 py-2 text-sm font-medium text-white hover:bg-green-600 focus:outline-none focus:ring-4 focus:ring-green-300"
                    >
                      Search
                    </button> */}
                  </div>
                </form>
              </div>

              <div>
                <button
                  onClick={async () => {
                    await supabase.auth.signOut();
                  }}
                >
                  Sign Out
                </button>
              </div>
            </div>
          </nav>
        ) : (
          <div class="flex h-screen items-center justify-center">
            <div class="text-center">
              <h1 class="text-white">App Name</h1>
              <button
                class="text-s inline-block rounded-full bg-spotifyGreen px-8 py-3 font-medium leading-tight text-white shadow-md transition duration-150 ease-in-out hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg"
                onClick={signInWithSpotify}
              >
                Log In with Spotify
              </button>
            </div>
          </div>
        )}
      </main>
    </>
  );
}
